### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by magicalsally** [magicalsally/magicalsally.io#7]
- [x] 入山法子、インタビュー記事 
- [x] Kプレス小林さまに連絡
- [x] きみぺ イベント試写会
- [ ] きみぺ、企画書 「おれはペット」
- [x] きみぺ打ち合わせ
- [ ] ゆきりんインタビュー記事公開のスケジュール
- [ ] PRESS編集部 月間スケジュール
- [x] PRESS編集部 土曜 記事更新
- [ ] PRESS 出版社の選定、予算だし
- [ ] PRESS スクリーンショットのラフ

**Comment by magicalsally** [comment]
## PRESS 編集部 記事

題材1：
新着オフィシャルブロガーのご紹介 #02【PICK UP】2/6-2/11 ：週間連載
```
https://pressblog.me/users/kk_aki
https://pressblog.me/users/puram77
https://pressblog.me/users/mizkixxjp
https://pressblog.me/users/ayayangram
https://pressblog.me/users/muratasaki
https://pressblog.me/users/laymeesao
https://pressblog.me/users/xxizumi123xx
https://pressblog.me/users/kao_roni
https://pressblog.me/users/mio_shioda
https://pressblog.me/users/ishidakazuho
```

**Comment by magicalsally** [comment]
## PRESS TODO
- [x] 月間スケジュール
- [x] スクショ、キャッチコピー
- [x] 企画あらいだし
- [x] ロケーション候補5つ選定
- [x] 内覧のスケジュール
- [x] ゆうこさん、LINEつなげてもらう
- [x] インタビューこたえてもらう @maimai 2/17
- [x] 貸スペース 候補選定 3つ @maimai 2/19

**Comment by magicalsally** [comment]
- [ ] サンプル記事の共有、MERY、vice_id
期限：2/22 18:00

- [ ] スクショの文言
期限：2/22 18:00
- [ ]  maimai にインタビュー写真データ送る 
期限：2/22 18:00
- [ ]  外部ライターとの編集フローの確立 ▶ ドキュメントつくる
期限：2/23 12:00
- [ ]  ゆうこちゃん github に連載概要まとめる
